import { createDefaultRegistry, getSceneType, validateSourcePresentation } from '../contracts/index.js';
import { themes } from '../themes/themes.js';

const clone = (value) => structuredClone(value);
const failure = (code, message, context = {}) => ({ ok: false, error: { code, message, context } });
const stamp = () => '2026-07-29T00:00:00Z';
const defaults = { cover: ['hero',['heading','Nueva presentación']], statement: ['centered',['heading','Nueva idea'],['paragraph','']], content: ['stack',['heading','Contenido'],['paragraph','']], media: ['media-right',['heading','Recurso'],['video','']], comparison: ['comparison',['heading','Comparación'],['comparison','']], evidence: ['evidence-grid',['metric','0'],['quote','']], closing: ['closing-callout',['heading','Cierre'],['callToAction','Continuar']] };
export function createStudioDraft({ id = 'studio-local', title = 'Nueva presentación', theme = 'nexus' } = {}) { return { contractVersion:'1.0.0', id, version:'1.0.0', minimumEngineVersion:'1.0.0', title, description:'', createdAt:stamp(), updatedAt:stamp(), theme, resources:[], scenes:[createScene('cover','scene-cover')] , editorial:{ studio:{ local:true } } }; }
export function createScene(type, id) { const spec = defaults[type]; if (!spec) return null; const [layout, ...blocks] = spec; return { id, type, layout, blocks: blocks.map(([blockType, text], index) => ({ id:`block-${id.replace('scene-','')}-${index + 1}`, type:blockType, ...(blockType === 'comparison' ? { left:'Antes',right:'Después' } : blockType === 'metric' ? { text, label:'Métrica' } : { text }) })) }; }
function historyEntry(draft) { const value = clone(draft), size = new TextEncoder().encode(JSON.stringify(value)).byteLength; return { value, size }; }
export function createStudioController({ draft = createStudioDraft(), maxActions = 50, maxBytes = 2 * 1024 * 1024 } = {}) {
  createDefaultRegistry(); let state, base, past = [], future = [], listeners = new Set(), destroyed = false;
  const derive = (next, dirty = JSON.stringify(next) !== JSON.stringify(base)) => { const validation = validateSourcePresentation(next), selectedSceneId = state?.selectedSceneId && next.scenes.some((scene)=>scene.id===state.selectedSceneId) ? state.selectedSceneId : null, selectedBlockId = selectedSceneId && state?.selectedBlockId && next.scenes.find((scene)=>scene.id===selectedSceneId)?.blocks.some((block)=>block.id===state.selectedBlockId) ? state.selectedBlockId : null; return { draft:clone(next), selectedSceneId, selectedBlockId, operation:null, messages:[], validation, valid:validation.valid, errorCount:validation.diagnostics.filter((x)=>x.severity==='error').length, dirty, canUndo:past.length>0, canRedo:future.length>0, preview:'future', export:'future' }; };
  base = clone(draft); state = derive(draft, false);
  const emit = () => { if (!destroyed) [...listeners].forEach((listener) => listener(clone(state))); };
  const ensure = () => destroyed ? failure('controller-destroyed','Studio controller was destroyed.') : null;
  const commit = (next) => { if (JSON.stringify(next) === JSON.stringify(state.draft)) return { ok:true, changed:false }; past.push(historyEntry(state.draft)); future=[]; while (past.length > maxActions || past.reduce((sum,item)=>sum+item.size,0) > maxBytes) past.shift(); state=derive(next); emit(); return { ok:true, changed:true }; };
  const uniqueId = (type) => `scene-${type}-${state.draft.scenes.length + 1}`;
  return {
    getState() { return clone(state); }, subscribe(listener) { if (destroyed || typeof listener !== 'function') return () => {}; listeners.add(listener); return () => listeners.delete(listener); },
    dispatch(command) { const gone=ensure(); if(gone)return gone; const draft=clone(state.draft), scenes=draft.scenes; if(!command?.type)return failure('invalid-operation','Command type is required.');
      if(command.type==='set-metadata'){ if(!['title','description'].includes(command.field)||draft[command.field]===command.value)return command.field ? {ok:true,changed:false}:failure('invalid-operation','Unsupported metadata field.'); draft[command.field]=String(command.value ?? ''); return commit(draft); }
      if(command.type==='set-theme'){ if(!themes[command.theme])return failure('unknown-theme','Theme is not registered.',{theme:command.theme}); draft.theme=command.theme; return commit(draft); }
      if(command.type==='add-resource'){ if(!command.resource?.id||draft.resources.some((item)=>item.id===command.resource.id))return failure('duplicate-resource','Resource id is missing or duplicated.'); draft.resources.push(clone(command.resource)); return commit(draft); }
      if(command.type==='remove-resource'){ const resourceIndex=draft.resources.findIndex((item)=>item.id===command.assetId);if(resourceIndex<0)return failure('resource-not-found','Resource does not exist.');const used=scenes.flatMap((scene)=>scene.blocks).some((block)=>[block.assetId,block.posterAssetId,block.captionsAssetId].includes(command.assetId));if(used)return failure('resource-in-use','Resource is still used by a scene.');draft.resources.splice(resourceIndex,1);return commit(draft); }
      if(command.type==='add-scene'){ const scene=createScene(command.sceneType,command.id ?? uniqueId(command.sceneType)); if(!scene||getSceneType(scene.type)===null)return failure('unknown-scene','Scene type is not registered.'); if(scenes.some((item)=>item.id===scene.id))return failure('duplicate-scene','Scene id is duplicated.'); scenes.splice(command.index ?? scenes.length,0,scene); return commit(draft); }
      const index=scenes.findIndex((item)=>item.id===command.id); if(index<0)return failure('scene-not-found','Scene does not exist.',{id:command.id});
      if(command.type==='remove-scene'){ scenes.splice(index,1); return commit(draft); } if(command.type==='move-scene'){ const to=command.to; if(!Number.isInteger(to)||to<0||to>=scenes.length)return failure('invalid-move','Destination is outside the scene list.'); scenes.splice(to,0,scenes.splice(index,1)[0]); return commit(draft); }
      if(command.type==='update-scene'){ const next={...scenes[index],...clone(command.patch)}; const definition=getSceneType(next.type); if(!definition||!definition.layouts.includes(next.layout))return failure('incompatible-layout','Layout is not valid for this scene.'); if((next.blocks??[]).some((block)=>!definition.blocks.includes(block.type)))return failure('unsupported-block','A block is not allowed in this scene.'); scenes[index]=next; return commit(draft); }
      return failure('invalid-operation','Unsupported command.'); },
    selectScene(id) { if(ensure())return false; if(id && !state.draft.scenes.some((scene)=>scene.id===id))return false; state={...state,selectedSceneId:id ?? null,selectedBlockId:null}; emit(); return true; }, selectBlock(id) { if(ensure())return false; state={...state,selectedBlockId:id ?? null}; emit(); return true; },
    canUndo(){return !destroyed&&past.length>0;},canRedo(){return !destroyed&&future.length>0;},undo(){const gone=ensure();if(gone)return gone;if(!past.length)return failure('history-unavailable','Nothing to undo.');future.unshift(historyEntry(state.draft));state=derive(past.pop().value);emit();return {ok:true};},redo(){const gone=ensure();if(gone)return gone;if(!future.length)return failure('history-unavailable','Nothing to redo.');past.push(historyEntry(state.draft));state=derive(future.shift().value);emit();return {ok:true};},markSaved(){if(ensure())return false;base=clone(state.draft);state=derive(state.draft,false);emit();return true;},reset(){if(ensure())return false;past=[];future=[];state=derive(base,false);emit();return true;},destroy(){destroyed=true;listeners.clear();past=[];future=[];state=null;}
  };
}
