export function createPlayerView(root, { player, renderers }) {
  root.innerHTML = `<main class="player" aria-labelledby="player-title"><p id="player-status" role="status"></p><section id="scene" aria-live="polite"><h1 id="player-title"></h1><p id="scene-body"></p></section><nav aria-label="Presentación"><button id="previous" type="button">Anterior</button><span id="progress"></span><button id="next" type="button">Siguiente</button><button id="restart" type="button">Reiniciar</button></nav></main>`;
  const $ = (id) => root.querySelector(`#${id}`), status = $('player-status'), title = $('player-title'), body = $('scene-body');
  const update = () => { const scene = player.getScene(), progress = player.getProgress(); const renderer = renderers.get(scene?.type); let output = { title: 'Escena no soportada', body: scene?.type ?? 'Sin escena' }; try { if (renderer) output = renderer.render(scene); } catch { status.textContent = 'Error al mostrar la escena'; output = { title: 'Escena no disponible', body: 'Intenta reiniciar o volver a cargar la presentación.' }; } title.textContent = output.title; body.textContent = output.body; $('progress').textContent = `${progress.current} de ${progress.total}`; $('previous').disabled = progress.current <= 1; $('next').disabled = player.getState() === 'completed'; };
  $('previous').onclick = () => player.previous(); $('next').onclick = () => player.next(); $('restart').onclick = () => player.restart();
  const subscriptions = [player.subscribe('presentation-loaded', () => { status.textContent = 'Lista'; update(); }), player.subscribe('scene-changed', update), player.subscribe('presentation-completed', () => { status.textContent = 'Presentación finalizada'; update(); }), player.subscribe('player-error', () => { status.textContent = 'Error al cargar la presentación'; })];
  const destroy = () => { subscriptions.forEach((unsubscribe) => unsubscribe()); root.replaceChildren(); };
  player.addCleanup(destroy); return { update, destroy };
}
