import test from 'node:test';
import assert from 'node:assert/strict';
import { bindKeyboard } from '../../src/input/keyboard.js';
import { bindTouch } from '../../src/input/touch.js';

function target() { const listeners = new Map(); return { addEventListener(type, fn) { listeners.set(type, fn); }, removeEventListener(type) { listeners.delete(type); }, fire(type, event) { listeners.get(type)?.(event); }, count() { return listeners.size; } }; }
const event = (key, tagName = 'DIV') => ({ key, target: { tagName }, preventDefault() {} });
test('keyboard navigates and ignores interactive elements', () => { const calls = [], node = target(), player = { next: () => calls.push('next'), previous: () => calls.push('previous'), restart: () => calls.push('restart'), pause: () => calls.push('pause'), getProgress: () => ({ total: 3 }), goToScene: (i) => calls.push(i) }; const cleanup = bindKeyboard(node, player); node.fire('keydown', event('ArrowRight')); node.fire('keydown', event('ArrowLeft')); node.fire('keydown', event('Home')); node.fire('keydown', event('End')); node.fire('keydown', event('ArrowRight', 'BUTTON')); assert.deepEqual(calls, ['next','previous','restart',2]); cleanup(); assert.equal(node.count(), 0); });
test('touch swipes horizontally and ignores vertical or short gestures', () => { const calls = [], node = target(), player = { next: () => calls.push('next'), previous: () => calls.push('previous') }, cleanup = bindTouch(node, player); const touch = (x, y) => ({ clientX: x, clientY: y }); node.fire('touchstart', { target: { tagName: 'DIV' }, touches: [touch(100, 0)] }); node.fire('touchend', { changedTouches: [touch(20, 2)] }); node.fire('touchstart', { target: { tagName: 'DIV' }, touches: [touch(20, 0)] }); node.fire('touchend', { changedTouches: [touch(100, 0)] }); node.fire('touchstart', { target: { tagName: 'DIV' }, touches: [touch(0, 0)] }); node.fire('touchend', { changedTouches: [touch(10, 90)] }); assert.deepEqual(calls, ['next','previous']); cleanup(); assert.equal(node.count(), 0); });
