import test from 'node:test';
import assert from 'node:assert/strict';
import { createDefaultRegistry } from '../../src/contracts/index.js';
import { createPlayer } from '../../src/player/player.js';
import { createRendererRegistry, createTextRenderers } from '../../src/player/renderers.js';
import { createPlayerView } from '../../src/ui/player-view.js';
import { demoPresentation } from '../../demo/public-demo.js';

function fakeRoot() { const ids = new Map(); const make = (id) => ({ id, textContent: '', disabled: false, onclick: null }); return { set innerHTML(_) { ['player-status','player-title','scene-body','previous','progress','next','restart'].forEach((id) => ids.set(id, make(id))); }, querySelector(selector) { return ids.get(selector.slice(1)); }, replaceChildren() { ids.clear(); }, ids }; }
function setup() { createDefaultRegistry(); const player = createPlayer(), registry = createRendererRegistry(), root = fakeRoot(); createTextRenderers().forEach((renderer) => registry.register(renderer)); const view = createPlayerView(root, { player, renderers: registry }); player.loadPresentation(demoPresentation); player.start(); return { player, root, view }; }
test('DOM adapter renders demo scenes, controls and progress visibly', () => { const { player, root } = setup(); assert.equal(root.ids.get('player-title').textContent, 'NEXUS'); assert.equal(root.ids.get('previous').disabled, true); assert.equal(root.ids.get('progress').textContent, '1 de 4'); root.ids.get('next').onclick(); assert.equal(root.ids.get('player-title').textContent, 'Narrativas web modulares'); assert.equal(root.ids.get('progress').textContent, '2 de 4'); player.goToScene(3); assert.equal(root.ids.get('next').disabled, false); root.ids.get('next').onclick(); assert.equal(root.ids.get('player-status').textContent, 'Presentación finalizada'); assert.equal(root.ids.get('next').disabled, true); root.ids.get('restart').onclick(); assert.equal(root.ids.get('progress').textContent, '1 de 4'); });
test('DOM adapter exposes invalid documents, unsupported renderers and renderer errors', () => { const player = createPlayer(), root = fakeRoot(), registry = createRendererRegistry(); createPlayerView(root, { player, renderers: registry }); player.loadPresentation({}); assert.equal(root.ids.get('player-status').textContent, 'Error al cargar la presentación'); createDefaultRegistry(); player.loadPresentation({ ...demoPresentation, scenes: [] }); assert.equal(root.ids.get('player-status').textContent, 'Error al cargar la presentación'); player.loadPresentation(demoPresentation); player.start(); assert.equal(root.ids.get('player-title').textContent, 'Escena no soportada'); registry.register({ typeId: 'cover', render() { throw new Error('renderer failure'); } }); player.restart(); assert.equal(root.ids.get('player-status').textContent, 'Error al mostrar la escena'); assert.equal(root.ids.get('player-title').textContent, 'Escena no disponible'); });

test('DOM adapter removes visible controls and subscriptions on destroy', () => { const { player, root } = setup(); player.destroy(); assert.equal(root.ids.size, 0); assert.equal(player.next(), false); });
